### ISSUE TITLE
[0.77.0-rc.1] Test Report 1

### ISSUE THREAD

**Issue by robhogan** [reactwg/react-native-releases#653]
### Target Minor

0.77.0-rc.1

### Tested configurations

Refer to this [spreadsheet](https://docs.google.com/spreadsheets/d/1p0Zs37ecau7Ty4L_4g1jf7PlivOmIEPjmDYq9Jp8qWI/edit?usp=sharing) for test cases.

- [x] RNTester + iOS + Hermes
- [x] RNTester + iOS + JSC
- [x] RNTester + Android + Hermes
- [ ] RNTester + Android + JSC
- [x] RNTestProject + iOS + Hermes
- [x] RNTestProject + iOS + JSC
- [x] RNTestProject + Android + Hermes
- [x] RNTestProject + Android + JSC

Close this issue if there are no blocking issues.

### Blocking Issues?

-

**Comment by robhogan** [comment]
Issue on launch with RNTester + Android + JSC:

```
12-03 14:59:14.394  2343  2343 F DEBUG   : Abort message: 'terminating due to uncaught exception of type facebook::jni::JniException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.react.devsupport.StackTraceHelper.convertParsedError(StackTraceHelper.java:271)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.react.runtime.ReactInstance$ReactJsExceptionHandlerImpl.reportJsException(ReactInstance.java:328)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.jni.NativeRunnable.run(Native Method)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at android.os.Handler.handleCallback(Handler.java:900)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at android.os.Handler.dispatchMessage(Handler.java:103)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at android.os.Looper.loop(Looper.java:219)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
12-03 14:59:14.394  2343  2343 F DEBUG   :     at java.lang.Thread.run(Thread.java:929)
```
